### ISSUE TITLE
Detect availbility of Managed Profile by resolving the Intent instead of DevicePolicManager API

### ISSUE THREAD

**Issue by licaon-kter** [PeterCxy/Shelter#1]
1.0, Mate9/Oreo

```
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: net.typeblog.shelter, PID: 23543
E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.app.action.PROVISION_MANAGED_PROFILE (has extras) }
E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1981)
E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1636)
E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4751)
E AndroidRuntime:        at android.support.v4.app.f.startActivityForResult(Unknown Source:10)
E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4691)
E AndroidRuntime:        at android.support.v4.app.f.startActivityForResult(Unknown Source:10)
E AndroidRuntime:        at net.typeblog.shelter.ui.i.onClick(Unknown Source:58)
E AndroidRuntime:        at android.support.v7.app.AlertController$b.handleMessage(Unknown Source:23)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:108)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:166)
E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7425)
E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

Am I missing an app?

**Comment by SkewedZeppelin** [comment]
You need to have a ROM that includes ManagedProvisioning. AOSP and LineageOS both include it.

After you grant Admin, Shelter will then launch ManagedProvisioning, which will launch the Android for Work setup wizard.

You do *not* need Google Play Services, Android for Work is one of the few new features actually included in AOSP.

**Comment by SkewedZeppelin** [comment]
Any official/stock Android 6.0+ ROM that includes Google Play passes CTS.
Android for Work support is a requirement to pass CTS afaik.
So if your device shipped with Google Play it should support Android for Work and this app.

Assuming your manufacturer hasn't butchered AOSP too much, you should be able to go to
Settings > Apps> See all apps > 3dot > Show System
there should be a "Work profile setup app" or an app with package ID `com.android.managedprovisioning`.

**Comment by licaon-kter** [comment]
Right, I might not have that then, or I managed to uninstall it.

Anyway, do catch these and show a proper dialogue: `Sorry you ROM does not have Managed...blahblah... EXIT`

**Comment by PeterCxy** [comment]
Since I can do absolutely nothing about missing managed profile feature in the ROM, I am closing it for now.

**Comment by PeterCxy** [comment]
Oh and by the way @licaon-kter, Shelter currently DOES detect the availability of this feature via the DevicePolicyManager API, and apparently your ROM reports that it supports the feature, while it actually doesn't.

**Comment by PeterCxy** [comment]
I'm reopening this to keep a reminder that I should detect the availability of managed profiles by resolving the intent rather than using the DevicePolicyManager API. Apparently our ROM makers are so fond of making things appear not broken while it is completely broken.

**Comment by PeterCxy** [comment]
fixed in master branch

**Comment by licaon-kter** [comment]
FYI, new ROM (without me fiddling) and Shelter works ;)
