### ISSUE TITLE
UX: Users should not be able to skip the setup dialog

### ISSUE THREAD

**Issue by licaon-kter** [PeterCxy/Shelter#2]
1.0, Mate9/Oreo

If I don't [press Continue](https://github.com/PeterCxy/Shelter/issues/1) and touch outside the dialogue, I can access the Settings view, but when I press ZZZ:
```
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: net.typeblog.shelter, PID: 23679
E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.typeblog.shelter/net.typeblog.shelter.ui.DummyActivity}: java.lang.IllegalStateException: Cannot find an intent in other profile
E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
E AndroidRuntime:        at android.app.ActivityThread.-wrap12(Unknown Source:0)
E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:108)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:166)
E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7425)
E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E AndroidRuntime: Caused by: java.lang.IllegalStateException: Cannot find an intent in other profile
E AndroidRuntime:        at net.typeblog.shelter.a.d.a(Unknown Source:65)
E AndroidRuntime:        at net.typeblog.shelter.ui.DummyActivity.onCreate(Unknown Source:522)
E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7372)
E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
E AndroidRuntime:        ... 9 more
W ActivityManager:   Force finishing activity net.typeblog.shelter/.ui.DummyActivity
W ActivityManager:   Force finishing activity net.typeblog.shelter/.ui.MainActivity
```

Am I missing something?

**Comment by PeterCxy** [comment]
This is expected, since your Work Profile hasn't been set up yet. However, you shouldn't be able to touch outside the dialog and simply skip it... This is a UX bug. I'm keeping this issue for now until I fix it.

**Comment by PeterCxy** [comment]
fixed in master branch
