### ISSUE TITLE
Whatsapp calls not working persistently

### ISSUE THREAD

**Issue by pixelyo** [PeterCxy/Shelter#34]
When making whatsapp calls from the sheltered app, i frequently run into the issue of not hearing my correspondent as well as my correspondent not hearing me.

After rebooting my device is usually works for one or two times. :/

It is interesting to note, that recording audio messages works persistently.

Those permissions are granted to sheltered whatsapp:
* Camera
* Contacts
* Microphone
* Phone
* Storage

**Comment by PeterCxy** [comment]
I have not seen this problem myself. Could anybody else reproduce this problem?

**Comment by azrdev** [comment]
I do have frequent crashes with whatsapp in shelter for some weeks/months now. This is "LineageOS for microG" on a Oneplus One, and by upgrading from LOS 16 to 17.1 this month the crashes became very frequent.

I captured the following log, not sure though (yet) if they all look the same:
~~~python traceback
01-15 14:31:51.039 17921 18125 I ActivityManager: Start proc 23243:com.google.android.gms/u10a22 for service {com.google.android.gms/org.microg.gms.wearable.WearableService}
01-15 14:31:51.261 19739 23282 D TextClassifierService: No configured system TextClassifierService
01-15 14:31:51.300 17921 18125 I ActivityManager: Start proc 23287:android.process.media/u10a5 for broadcast {com.android.providers.media/com.android.providers.media.MediaReceiver}
01-15 14:31:51.406 17921 17979 W ActivityManager: Permission Denial: opening provider com.whatsapp.contentprovider.MediaProvider from ProcessRecord{461b70a 18448:com.android.systemui/u0a11} (pid=18448, uid=10011) that is not exported fr
om UID 10136
--------- beginning of crash
01-15 14:31:51.434 17921 17921 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
01-15 14:31:51.434 17921 17921 E AndroidRuntime: java.lang.SecurityException: UID 1010136 does not have permission to content://media/external/audio/media/15626 [user 0]
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermission(UriGrantsManagerService.java:1179)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.server.uri.UriGrantsManagerService.grantUriPermission(UriGrantsManagerService.java:767)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.server.uri.UriGrantsManagerService.grantUriPermissionFromOwner(UriGrantsManagerService.java:208)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.server.notification.NotificationManagerService.grantUriPermission(NotificationManagerService.java:6937)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.server.notification.NotificationManagerService.updateUriPermissions(NotificationManagerService.java:6909)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.server.notification.NotificationManagerService$NotificationListeners.notifyPostedLocked(NotificationManagerService.java:8303)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.server.notification.NotificationManagerService$NotificationListeners.notifyPostedLocked(NotificationManagerService.java:8249)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.server.notification.NotificationManagerService$PostNotificationRunnable.run(NotificationManagerService.java:5680)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:558)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:356)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-15 14:31:51.434 17921 17921 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)
01-15 14:31:51.436 17921 17921 I DropBoxManagerService: add tag=system_server_crash isTagEnabled=true flags=0x2
01-15 14:31:51.528 23287 23310 E AndroidRuntime: FATAL EXCEPTION: IntentService[MediaProvider]
01-15 14:31:51.528 23287 23310 E AndroidRuntime: Process: android.process.media, PID: 23287
01-15 14:31:51.528 23287 23310 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
01-15 14:31:51.532 18448 18448 E AndroidRuntime: FATAL EXCEPTION: main
01-15 14:31:51.532 18448 18448 E AndroidRuntime: Process: com.android.systemui, PID: 18448
01-15 14:31:51.532 18448 18448 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
01-15 14:31:52.111 23315 23318 D BootAnimation: BootAnimationShownTiming start time: 168422712ms
~~~

**Comment by PeterCxy** [comment]
@azrdev Thank you for the log. It looks like your WhatsApp is trying to access media storage which got rejected by the system for some reason and then crashed. What were you trying to do when this happened?

**Comment by azrdev** [comment]
> It looks like your WhatsApp is trying to access media storage which got rejected by the system for some reason and then crashed. What were you trying to do when this happened?

sometimes nothing (it even crashes when the screen is locked and off). I think it correlates to whatsapp receiving a audio/video message and displaying a corresponding notification (which is also enabled on the lockscreen, in my case)
